/*
 * This file is generated by jOOQ.
 */
package io.ehdev.gadget.db.tables.pojos;


import java.io.Serializable;
import java.time.Instant;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "redirect_history", schema = "gadget", indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "redirect_history_id ASC")
})
public class RedirectHistory implements Serializable {

    private static final long serialVersionUID = 45536828;

    private Long    redirectHistoryId;
    private String  alias;
    private String  variables;
    private String  destination;
    private String  user;
    private Instant deletedAt;

    public RedirectHistory() {}

    public RedirectHistory(RedirectHistory value) {
        this.redirectHistoryId = value.redirectHistoryId;
        this.alias = value.alias;
        this.variables = value.variables;
        this.destination = value.destination;
        this.user = value.user;
        this.deletedAt = value.deletedAt;
    }

    public RedirectHistory(
        Long    redirectHistoryId,
        String  alias,
        String  variables,
        String  destination,
        String  user,
        Instant deletedAt
    ) {
        this.redirectHistoryId = redirectHistoryId;
        this.alias = alias;
        this.variables = variables;
        this.destination = destination;
        this.user = user;
        this.deletedAt = deletedAt;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "redirect_history_id", unique = true, nullable = false, precision = 19)
    public Long getRedirectHistoryId() {
        return this.redirectHistoryId;
    }

    public void setRedirectHistoryId(Long redirectHistoryId) {
        this.redirectHistoryId = redirectHistoryId;
    }

    @Column(name = "alias", nullable = false, length = 256)
    @NotNull
    @Size(max = 256)
    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    @Column(name = "variables", length = 256)
    @Size(max = 256)
    public String getVariables() {
        return this.variables;
    }

    public void setVariables(String variables) {
        this.variables = variables;
    }

    @Column(name = "destination", nullable = false, length = 4096)
    @NotNull
    @Size(max = 4096)
    public String getDestination() {
        return this.destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    @Column(name = "user", nullable = false, length = 256)
    @NotNull
    @Size(max = 256)
    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    @Column(name = "deleted_at", nullable = false)
    public Instant getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Instant deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RedirectHistory (");

        sb.append(redirectHistoryId);
        sb.append(", ").append(alias);
        sb.append(", ").append(variables);
        sb.append(", ").append(destination);
        sb.append(", ").append(user);
        sb.append(", ").append(deletedAt);

        sb.append(")");
        return sb.toString();
    }
}
