# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-16.04'

trigger: ['master']
steps:
  - script: |
      curl --location https://github.com/ethankhall/inc/releases/download/v0.1.6/inc-linux-0.1.6 -o ~/inc
      curl --location https://github.com/ethankhall/release-manager/releases/download/v0.1.9/release-manager-linux -o ~/release-manager
      chmod +x ~/inc ~/release-manager
      ~/inc exec build
    displayName: 'Prepare the machine'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'

  - task: CopyFiles@2
    inputs:
      contents: build/webapp/gadget-release/
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: gadget.zip

  - script: |
      GCR_PW="$(echo $GCP_SERVICE_TOKEN | base64 -d)"
      ./gradlew jib -Djib.to.auth.password=$GCR_PW
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

