[versions]
kotlin = { version = "1.2.51", group = "org.jetbrains.kotlin" }
jackson = { version = "2.9.6", group = "com.fasterxml.jackson.core" }
jacksonData = { version = "2.9.6", group = "com.fasterxml.jackson.datatype" }
jacksonModule = { version = "2.9.6", group = "com.fasterxml.jackson.module" }
spring = { version = "5.0.8.RELEASE", group = "org.springframework" }
springBoot = { version = "2.0.4.RELEASE", group = "org.springframework.boot" }

[libraries]
kotlin = [
    "org.jetbrains.kotlin:kotlin-stdlib",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
    "org.jetbrains.kotlin:kotlin-reflect"
]
logging = [
    "org.slf4j:slf4j-api:1.7.25",
    'org.apache.logging.log4j:log4j-core:2.11.1',
    'org.apache.logging.log4j:log4j-slf4j18-impl:2.11.1'
]

spring = [
    'org.springframework:spring-context',
    'org.springframework:spring-webflux',
    'org.springframework:spring-tx',
    'org.springframework:spring-jdbc',
    'org.springframework:spring-context-support',
    'io.projectreactor.ipc:reactor-netty:0.7.8.RELEASE',
    'org.springframework.boot:spring-boot',
    'org.springframework.boot:spring-boot-autoconfigure',
    'org.springframework.boot:spring-boot-starter'
]

httpClient = [
    'io.projectreactor.ipc:reactor-netty:0.7.8.RELEASE',
    'io.mikael:urlbuilder:2.0.9'
]

database = [
    "mysql:mysql-connector-java:8.0.11",
    "com.zaxxer:HikariCP:2.4.1",
    "org.jooq:jooq:3.11.3",
    "org.jooq:jooq-meta:3.11.3",
    "org.flywaydb:flyway-core:4.1.2"
]

commonsLang = [
        "org.apache.commons:commons-lang3:3.7"
]
jackson = [
        "com.fasterxml.jackson.core:jackson-annotations",
        "com.fasterxml.jackson.core:jackson-databind",
        "com.fasterxml.jackson.datatype:jackson-datatype-jsr310",
        "com.fasterxml.jackson.module:jackson-module-kotlin"
]

jooqCodeGen = [
    "org.jooq:jooq:3.11.3",
    "org.jooq:jooq-meta:3.11.3",
    "org.jooq:jooq-codegen:3.11.3",
    "mysql:mysql-connector-java:8.0.11"
]
testingLibraries = [
    "org.mockito:mockito-core:1.10.19",
    "com.jayway.jsonpath:json-path:2.2.0",
    "cglib:cglib:3.2.5",
    "org.objenesis:objenesis:2.2",
    "org.ow2.asm:asm:5.0.4",
    "de.sven-jacobs:loremipsum:1.0",
    "org.jetbrains.kotlin:kotlin-test-junit5:1.2.51",
    'com.github.tomakehurst:wiremock:2.18.0'
    'org.hamcrest:hamcrest-library:1.3'
]