/*
 * This file is generated by jOOQ.
 */
package io.ehdev.gadget.db;


import io.ehdev.gadget.db.tables.FlywaySchemaHistoryTable;
import io.ehdev.gadget.db.tables.RedirectHistoryTable;
import io.ehdev.gadget.db.tables.RedirectTable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gadget extends SchemaImpl {

    private static final long serialVersionUID = 1504654326;

    /**
     * The reference instance of <code>gadget</code>
     */
    public static final Gadget GADGET = new Gadget();

    /**
     * The table <code>gadget.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistoryTable FLYWAY_SCHEMA_HISTORY = io.ehdev.gadget.db.tables.FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>gadget.redirect</code>.
     */
    public final RedirectTable REDIRECT = io.ehdev.gadget.db.tables.RedirectTable.REDIRECT;

    /**
     * The table <code>gadget.redirect_history</code>.
     */
    public final RedirectHistoryTable REDIRECT_HISTORY = io.ehdev.gadget.db.tables.RedirectHistoryTable.REDIRECT_HISTORY;

    /**
     * No further instances allowed
     */
    private Gadget() {
        super("gadget", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY,
            RedirectTable.REDIRECT,
            RedirectHistoryTable.REDIRECT_HISTORY);
    }
}
