/*
 * This file is generated by jOOQ.
 */
package io.ehdev.gadget.db;


import io.ehdev.gadget.db.tables.FlywaySchemaHistoryTable;
import io.ehdev.gadget.db.tables.RedirectHistoryTable;
import io.ehdev.gadget.db.tables.RedirectTable;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>gadget</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index FLYWAY_SCHEMA_HISTORY_PRIMARY = Indexes0.FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final Index REDIRECT_ALIAS = Indexes0.REDIRECT_ALIAS;
    public static final Index REDIRECT_PRIMARY = Indexes0.REDIRECT_PRIMARY;
    public static final Index REDIRECT_HISTORY_PRIMARY = Indexes0.REDIRECT_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createIndex("PRIMARY", FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index REDIRECT_ALIAS = Internal.createIndex("alias", RedirectTable.REDIRECT, new OrderField[] { RedirectTable.REDIRECT.ALIAS }, true);
        public static Index REDIRECT_PRIMARY = Internal.createIndex("PRIMARY", RedirectTable.REDIRECT, new OrderField[] { RedirectTable.REDIRECT.REDIRECT_ID }, true);
        public static Index REDIRECT_HISTORY_PRIMARY = Internal.createIndex("PRIMARY", RedirectHistoryTable.REDIRECT_HISTORY, new OrderField[] { RedirectHistoryTable.REDIRECT_HISTORY.REDIRECT_HISTORY_ID }, true);
    }
}
