/*
 * This file is generated by jOOQ.
 */
package io.ehdev.gadget.db;


import io.ehdev.gadget.db.tables.FlywaySchemaHistoryTable;
import io.ehdev.gadget.db.tables.RedirectHistoryTable;
import io.ehdev.gadget.db.tables.RedirectTable;
import io.ehdev.gadget.db.tables.records.FlywaySchemaHistoryRecord;
import io.ehdev.gadget.db.tables.records.RedirectHistoryRecord;
import io.ehdev.gadget.db.tables.records.RedirectRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>gadget</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RedirectRecord, Long> IDENTITY_REDIRECT = Identities0.IDENTITY_REDIRECT;
    public static final Identity<RedirectHistoryRecord, Long> IDENTITY_REDIRECT_HISTORY = Identities0.IDENTITY_REDIRECT_HISTORY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = UniqueKeys0.KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final UniqueKey<RedirectRecord> KEY_REDIRECT_PRIMARY = UniqueKeys0.KEY_REDIRECT_PRIMARY;
    public static final UniqueKey<RedirectRecord> KEY_REDIRECT_ALIAS = UniqueKeys0.KEY_REDIRECT_ALIAS;
    public static final UniqueKey<RedirectHistoryRecord> KEY_REDIRECT_HISTORY_PRIMARY = UniqueKeys0.KEY_REDIRECT_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RedirectRecord, Long> IDENTITY_REDIRECT = Internal.createIdentity(RedirectTable.REDIRECT, RedirectTable.REDIRECT.REDIRECT_ID);
        public static Identity<RedirectHistoryRecord, Long> IDENTITY_REDIRECT_HISTORY = Internal.createIdentity(RedirectHistoryTable.REDIRECT_HISTORY, RedirectHistoryTable.REDIRECT_HISTORY.REDIRECT_HISTORY_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, "KEY_flyway_schema_history_PRIMARY", FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<RedirectRecord> KEY_REDIRECT_PRIMARY = Internal.createUniqueKey(RedirectTable.REDIRECT, "KEY_redirect_PRIMARY", RedirectTable.REDIRECT.REDIRECT_ID);
        public static final UniqueKey<RedirectRecord> KEY_REDIRECT_ALIAS = Internal.createUniqueKey(RedirectTable.REDIRECT, "KEY_redirect_alias", RedirectTable.REDIRECT.ALIAS);
        public static final UniqueKey<RedirectHistoryRecord> KEY_REDIRECT_HISTORY_PRIMARY = Internal.createUniqueKey(RedirectHistoryTable.REDIRECT_HISTORY, "KEY_redirect_history_PRIMARY", RedirectHistoryTable.REDIRECT_HISTORY.REDIRECT_HISTORY_ID);
    }
}
