/*
 * This file is generated by jOOQ.
 */
package io.ehdev.gadget.db;


import io.ehdev.gadget.db.tables.FlywaySchemaHistoryTable;
import io.ehdev.gadget.db.tables.RedirectHistoryTable;
import io.ehdev.gadget.db.tables.RedirectTable;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in gadget
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>gadget.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistoryTable FLYWAY_SCHEMA_HISTORY = io.ehdev.gadget.db.tables.FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>gadget.redirect</code>.
     */
    public static final RedirectTable REDIRECT = io.ehdev.gadget.db.tables.RedirectTable.REDIRECT;

    /**
     * The table <code>gadget.redirect_history</code>.
     */
    public static final RedirectHistoryTable REDIRECT_HISTORY = io.ehdev.gadget.db.tables.RedirectHistoryTable.REDIRECT_HISTORY;
}
